version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root-1
      - DB_PASSWORD=Krishna8kichu@
      - DB_NAME=my_db
  frontend:
    build: ./frontend/frontends
    ports:
      - "3000:80"   # Or "80:80" if serving with Nginx
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Krishna8kichu@
      MYSQL_DATABASE: my_db
      MYSQL_USER: root-1
      MYSQL_PASSWORD: Krishna8kichu@
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  mysqldb_exporter:
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "root-1:Krishna8kichu%40@(db:3306)/"
    ports:
      - "9104:9104"
    depends_on:
      - db
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro    # read-only permissions
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb_exporter
      - backend
  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  db_data:
  grafana_data: