version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=appuser
      - DB_PASSWORD=appsecret
      - DB_NAME=classicmodels
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"   # Or "80:80" if serving with Nginx
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: classicmodels
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appsecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: