services:
  backend:
    build: ./backend
    ports: ['5000:5000']
    depends_on: ['db']
  frontend:
    build: ./frontend
    ports: ['3000:3000']
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
